-- 001_init.sql
-- Purpose: Initialize database schema(tables, keys, relationships, constraints)
-- Target DB: PostgreSQL (supabase-compatible)
-- Run order: 001_init.sql -> 002_seed_data.sql -> 003_triggers.sql -> 004_views.sql -> 005_queries.sql

CREATE TYPE "APPOINTMENT_STATUS" AS ENUM (
  'Pending',
  'Cancelled',
  'Complete'
);

CREATE TYPE "STAFF_ROLE" AS ENUM (
  'Doctor',
  'Receptionist',
  'Administrator'
);

CREATE TABLE "PATIENT" (
  "patient_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "phone" varchar(10) UNIQUE NOT NULL
);

CREATE TABLE "STAFF" (
  "staff_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "phone" varchar(10) UNIQUE NOT NULL,
  "role" "STAFF_ROLE" NOT NULL
);

CREATE TABLE "SERVICE" (
  "service_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "service_name" varchar NOT NULL,
  "service_cost" decimal(10,2)
);

CREATE TABLE "APPOINTMENT" (
  "appointment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" int NOT NULL,
  "staff_id" int NOT NULL,
  "appointment_date" date NOT NULL,
  "appointment_time" time NOT NULL,
  "appointment_status" "APPOINTMENT_STATUS" NOT NULL
);

CREATE TABLE "MEDICAL_RECORD" (
  "record_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" int NOT NULL,
  "appointment_id" int NOT NULL,
  "visit_notes" varchar,
  "diagnosis" varchar,
  "admission_date" date,
  "discharge_date" date 
);

CREATE TABLE "APPOINTMENT_SERVICE" (
  "appointment_service_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "appointment_id" int NOT NULL,
  "service_id" int NOT NULL
);

CREATE TABLE "INVOICE" (
  "invoice_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "appointment_id" int NOT NULL,
  "total_amount" decimal(10,2)
);

CREATE TABLE "PAYMENT" (
  "payment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "invoice_id" int NOT NULL,
  "payment_amount" decimal(10,2),
  "payment_date" date
);

ALTER TABLE "APPOINTMENT" ADD FOREIGN KEY ("patient_id") REFERENCES "PATIENT" ("patient_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "APPOINTMENT" ADD FOREIGN KEY ("staff_id") REFERENCES "STAFF" ("staff_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "MEDICAL_RECORD" ADD FOREIGN KEY ("patient_id") REFERENCES "PATIENT" ("patient_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "MEDICAL_RECORD" ADD FOREIGN KEY ("appointment_id") REFERENCES "APPOINTMENT" ("appointment_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "APPOINTMENT_SERVICE" ADD FOREIGN KEY ("appointment_id") REFERENCES "APPOINTMENT" ("appointment_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "APPOINTMENT_SERVICE" ADD FOREIGN KEY ("service_id") REFERENCES "SERVICE" ("service_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "INVOICE" ADD FOREIGN KEY ("appointment_id") REFERENCES "APPOINTMENT" ("appointment_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PAYMENT" ADD FOREIGN KEY ("invoice_id") REFERENCES "INVOICE" ("invoice_id") DEFERRABLE INITIALLY IMMEDIATE;
